add moshi classes for webfinger responses
owncloud/android-library pull request #481
Opened 2022-04-20 13:14 UTC by theScrabi

Issue: https://github.com/owncloud/enterprise/issues/5021#issuecomment-1102692271
App:

2022-10-11 16:19 UTC, JuancaG05 requested changes
Some spelling and minor suggestions, good job! 👍

2022-10-11 16:19 UTC, JuancaG05 commented on owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/webfinger/responses/WebfingerResponse.kt
> +)
Better end with a blank line 👍

2022-10-11 16:19 UTC, JuancaG05 commented on owncloudComLibrary/src/test/java/com/owncloud/android/lib/resources/webfinger/responses/WebfingerResponseTest.kt
> +    fun `check rel in to much information - ok - correct rell is returned`() {
I don't understand very well the name of this test, what does `rel` or `rell` refer to? Is it `to` or `too`? I would change its name, don't you think?
Also, when the test is for a correct case (`ok`, like in this case), do we put additional information like `correct rell is returned` if it is evident?

2022-10-11 16:19 UTC, JuancaG05 commented on owncloudComLibrary/src/test/java/com/owncloud/android/lib/resources/webfinger/responses/WebfingerResponseTest.kt
> +        val TO_MUCH_INFORMATION_JSON = "$RESOURCES_PATH/to_much_information_response.json"
Same as in the test, I guess this is `TOO_...`

2022-10-11 16:19 UTC, JuancaG05 commented on owncloudComLibrary/src/test/responses/com.owncloud.android.lib.resources.webfinger.responses/not_containing_releavant_info_response.json
> +}
Add final blank line. Also, I think the name of this file doesn't fit with the name that is used in the tests. In this case, it is called `..._releavant_...`, it should be "relevant", is that correct?

2022-10-11 16:19 UTC, JuancaG05 commented on owncloudComLibrary/src/test/responses/com.owncloud.android.lib.resources.webfinger.responses/to_much_information_response.json
> +}
Final blank line 😀

2022-10-13 08:20 UTC, abelgardep commented on owncloudComLibrary/src/test/responses/com.owncloud.android.lib.resources.webfinger.responses/to_much_information_response.json
> +}
Not relevant at all for the tests

2022-10-13 08:48 UTC, JuancaG05 approved these changes

2022-11-02 10:16 UTC, merged